Repository github/combine-prs, pull requests merged in 2023-03, with the labels that each got.

#6 Branch Already Exists - Error Handling
  __tests__/main.test.js
  dist/index.js
  dist/index.js.map
  src/main.js
Labels: bug, enhancement

#9 if the combined pr already exists, just update it
  __tests__/main.test.js
  dist/index.js
  dist/index.js.map
  src/main.js
Labels: bug

#10 Re-Open Closed PRs
  __tests__/main.test.js
  dist/index.js
  dist/index.js.map
  src/main.js
Labels: enhancement

#12 Add `select_label` option
  README.md
  __tests__/main.test.js
  action.yml
  dist/index.js
  dist/index.js.map
  src/main.js
Labels: enhancement

#13 Only combine PRs if more than one exists
  README.md
  __tests__/main.test.js
  action.yml
  dist/index.js
  dist/index.js.map
  src/main.js
Labels: enhancement

#15 Repo Updates
  .github/CODEOWNERS
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yml
  .github/workflows/package-check.yml
  .github/workflows/test.yml
  README.md
  dist/index.js
  dist/index.js.map
  docs/assets/example.png
  package-lock.json
  package.json
Labels: documentation, enhancement

#14 Fix select label override
  __tests__/main.test.js
  dist/index.js
  dist/index.js.map
  src/main.js
Labels: bug, enhancement
